parameters:
  site:
    my-domain.dp.loc.wip: {
      id: 1,
      main_page_entity_id: 1,
      status: 1,
      max_preview_pages_on_main: 5,
      max_preview_pages: 10,
      datetime_format: 'h:i d/m/Y',
      datetime_format_js: 'HH:MM DD/MM/YYYY',
    },
    127.0.0.1: {
      id: 2,
      main_page_entity_id: 1,
      status: 1,
      max_preview_pages_on_main: 5,
      max_preview_pages: 10
    }